version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.50.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Build app
          command: "cargo build --verbose"
      - run:
          name: Run Tests
          command: "cargo test --verbose"
